plugins {
    id 'com.android.application'
    id 'com.mikepenz.aboutlibraries.plugin'
}

android {
    namespace 'com.manager.ssb'
    compileSdk 36
    ndkVersion = "28.2.13676358"
    
    buildFeatures {
        buildConfig true
    }
    
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    
    signingConfigs {
        release {
            storeFile null
            keyAlias null
        }
        
        debug {
            storeFile null
            keyAlias null
        }
    }
    
    // 从外部文件加载签名配置（如果存在）
    def keystorePropertiesFile = rootProject.file('keystore.properties')
    if (keystorePropertiesFile.exists()) {
        def keystoreProperties = new Properties()
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
        
        signingConfigs.release.storeFile = file(keystoreProperties['storeFile'])
        signingConfigs.release.storePassword = keystoreProperties['storePassword']
        signingConfigs.release.keyAlias = keystoreProperties['keyAlias']
        signingConfigs.release.keyPassword = keystoreProperties['keyPassword']
        
        signingConfigs.debug.storeFile = file(keystoreProperties['storeFile'])
        signingConfigs.debug.storePassword = keystoreProperties['storePassword']
        signingConfigs.debug.keyAlias = keystoreProperties['keyAlias']
        signingConfigs.debug.keyPassword = keystoreProperties['keyPassword']
    }

    defaultConfig {
        applicationId "com.manager.ssb"
        minSdk 23
        targetSdk 28
        versionCode 2
        versionName "1.0.1"
        
        multiDexEnabled true
        
        vectorDrawables { 
            useSupportLibrary true
        }
        
        externalNativeBuild {
            ndkBuild {
                cFlags "-Os", "-fno-stack-protector", "-Wl,--gc-sections"
            }
        }

        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
        }
        
        def getGitInfo = { commandParts ->
            def proc = commandParts.execute([], project.rootDir)
            def output = new ByteArrayOutputStream()
            def error = new ByteArrayOutputStream()
            proc.waitForProcessOutput(output, error)
            if (proc.exitValue() != 0) {
                logger.error("Git command failed: ${commandParts.join(' ')}\nError: ${error.toString()}")
                return "unknown"
            }
            return output.toString().trim()
        }

        def gitBranchName = getGitInfo(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])
        def gitCommitShortHash = getGitInfo(['git', 'rev-parse', '--short', 'HEAD'])
        def gitCommitAuthor = getGitInfo(['git', 'log', '-1', '--pretty=format:%an'])
        def gitCommitTime = getGitInfo(['git', 'log', '-1', '--pretty=format:%ct'])

        buildConfigField "String", "GIT_BRANCH_NAME", "\"${gitBranchName}\""
        buildConfigField "String", "GIT_COMMIT_SHORT_HASH", "\"${gitCommitShortHash}\""
        buildConfigField "String", "GIT_COMMIT_AUTHOR", "\"${gitCommitAuthor}\""
        buildConfigField "String", "GIT_COMMIT_TIME", "\"${gitCommitTime}\""
        
        buildConfigField "String", "SIGNATURE_MD5", "\"a69c66db66302c7b55ca797f7da81404\""
        
        buildConfigField "String", "BUILD_TIME", "\"${System.currentTimeMillis()}\""
        buildConfigField("String", "APPLICATION_ID_SUFFIX", "\"\"")
    }

    buildTypes {
        debug {
            def getGitInfo = { commandParts ->
                def proc = commandParts.execute([], project.rootDir)
                def output = new ByteArrayOutputStream()
                def error = new ByteArrayOutputStream()
                proc.waitForProcessOutput(output, error)
                if (proc.exitValue() != 0) {
                    logger.error("Git command failed: ${commandParts.join(' ')}\nError: ${error.toString()}")
                    return "unknown"
                }
                return output.toString().trim()
            }
            
            def gitCommitShortHash = getGitInfo(['git', 'rev-parse', '--short', 'HEAD'])
            
            // 动态生成版本名称，追加 Build 号
            def buildNumberFile = file("${project.rootDir}/buildNumber.txt")
            def buildNumber = 0 // 默认构建号

            // 如果 buildNumber 文件存在，读取其中的值
            if (buildNumberFile.exists()) {
                buildNumber = Integer.parseInt(buildNumberFile.text.trim())
            } else {
                // 如果文件不存在，初始化为0
                buildNumberFile.text = "0"
            }
            

            // 组合版本后缀
            versionNameSuffix "-build${buildNumber + 1}.${gitCommitShortHash}"

            // 在构建完成后递增 buildNumber 并写入文件
            tasks.whenTaskAdded { task ->
                if (task.name == 'assembleDebug') {
                    task.doLast {
                        // 更新 buildNumber 文件
                        buildNumber = buildNumber + 1
                        buildNumberFile.text = buildNumber.toString()
                    }
                }
            }
            
            signingConfig signingConfigs.debug
        }
        
        release {
            def getGitInfo = { commandParts ->
                def proc = commandParts.execute([], project.rootDir)
                def output = new ByteArrayOutputStream()
                def error = new ByteArrayOutputStream()
                proc.waitForProcessOutput(output, error)
                if (proc.exitValue() != 0) {
                    logger.error("Git command failed: ${commandParts.join(' ')}\nError: ${error.toString()}")
                    return "unknown"
                }
                return output.toString().trim()
            }
            
            def gitCommitShortHash = getGitInfo(['git', 'rev-parse', '--short', 'HEAD'])
            
            // 动态生成版本名称，追加 Build 号
            def buildNumberFile = file("${project.rootDir}/buildNumber.txt")
            def buildNumber = 0 // 默认构建号

            // 如果 buildNumber 文件存在，读取其中的值
            if (buildNumberFile.exists()) {
                buildNumber = Integer.parseInt(buildNumberFile.text.trim())
            } else {
                // 如果文件不存在，初始化为0
                buildNumberFile.text = "0"
            }
            
            def releaseNumberFile = file("${project.rootDir}/releaseNumber.txt")
            def releaseNumber = 0 // 默认构建号

            // 如果 buildNumber 文件存在，读取其中的值
            if (releaseNumberFile.exists()) {
                releaseNumber = Integer.parseInt(releaseNumberFile.text.trim())
            } else {
                // 如果文件不存在，初始化为0
                releaseNumberFile.text = "0"
            }
            
            versionNameSuffix "-release${releaseNumber + 1}-build${buildNumber + 1}.${gitCommitShortHash}"
            
            // 在构建完成后递增 buildNumber 并写入文件
            tasks.whenTaskAdded { task ->
                if (task.name == 'assembleRelease') {
                    task.doLast {
                        // 更新 buildNumber 文件
                        buildNumber = buildNumber + 1
                        buildNumberFile.text = buildNumber.toString()
                        
                        // 更新 releaseNumber 文件
                        releaseNumber = releaseNumber + 1
                        releaseNumberFile.text = releaseNumber.toString()
                    }
                }
            }
            
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            
            // 配置签名
            signingConfig signingConfigs.release
        }
    }
    

    compileOptions {
        // 启用核心库脱糖
        coreLibraryDesugaringEnabled true
        
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        compose true
    }
    
    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }
    
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    // 核心库脱糖依赖
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
    
    // AndroidX 核心库
    implementation 'androidx.activity:activity:1.12.4'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.appcompat:appcompat-resources:1.7.1'
    implementation 'com.github.halifox:androidx.preference.material3:1.2.1-alpha07'
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.fragment:fragment:1.8.9'
    
    // Google Material 设计
    implementation 'com.google.android.material:material:1.14.0-alpha09'
    
    // JSON 处理
    implementation 'com.google.code.gson:gson:2.8.8'
    
    // 布局
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Sora Editor
    implementation 'io.github.Rosemoe.sora-editor:editor:0.23.4'
    implementation 'io.github.Rosemoe.sora-editor:language-textmate:0.23.4'
    implementation 'io.github.Rosemoe.sora-editor:language-java:0.23.4'
    
    // WebView
    implementation 'androidx.webkit:webkit:1.7.0'
    
    // libarchive
    implementation 'me.zhanghai.android.libarchive:library:1.1.6'
    
    // Lua 脚本引擎, 用于plugin
    implementation 'org.luaj:luaj-jse:3.0.1'
    
    implementation 'com.mikepenz:aboutlibraries:10.0.0'
    implementation "com.mikepenz:aboutlibraries-core:10.0.0"
    
    // 项目模块
    api project(":terminal-view")
}

afterEvaluate {
    // 为每个变体创建复制任务，并确保在 preBuild 之前执行
    android.applicationVariants.all { variant ->
        def variantName = variant.name.capitalize()
        def variantNameLower = variant.name

        // 插件实际生成 JSON 的任务
        def prepareTask = tasks.findByName("prepareLibraryDefinitions${variantName}")

        if (prepareTask) {
            def copyTask = tasks.register("copyAboutLibrariesJson${variantName}", Copy) {
                dependsOn prepareTask
                from "$buildDir/generated/aboutLibraries/${variantNameLower}/res/raw/aboutlibraries.json"
                into "src/main/res/raw/"
            }

            // 让 preBuild 任务等待复制完成
            tasks.named('preBuild').configure {
                dependsOn copyTask
            }
        } else {
            // 如果找不到 prepare 任务（理论上不会），打印警告并尝试手动指定源
            logger.warn("prepareLibraryDefinitions${variantName} task not found, AboutLibraries may not show data.")
        }
    }
}